# MPWR Position Configuration

TICKER = "MPWR"
SHARES = 925
CONTRACTS = 9
SHARES_PER_CONTRACT = 100
COVERED_SHARES = CONTRACTS * SHARES_PER_CONTRACT  # 900
UNCOVERED_SHARES = SHARES - COVERED_SHARES  # 25

# Dividend info
QUARTERLY_DIVIDEND_PER_SHARE = 1.50  # approximate, trending upward
ANNUAL_DIVIDEND_PER_SHARE = QUARTERLY_DIVIDEND_PER_SHARE * 4
QUARTERLY_DIVIDEND_INCOME = SHARES * QUARTERLY_DIVIDEND_PER_SHARE
ANNUAL_DIVIDEND_INCOME = SHARES * ANNUAL_DIVIDEND_PER_SHARE